# Generated by Django 5.1.4 on 2025-01-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_blogs.blogmodel', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
    ]
