# Generated by Django 5.1.4 on 2025-02-03 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image1',
            field=models.ImageField(upload_to='products', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])], verbose_name='image1'),
        ),
    ]
