# Generated by Django 5.1.4 on 2025-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_alter_productmodel_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmanufacturemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='productmanufacturemodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
